// Catálogo de ítems para la mascota
// Puedes agregar más categorías, efectos y emojis según lo necesites

export type PetItemCategory = 'food' | 'toy' | 'furniture' | 'clothing' | 'accessory' | 'eyes' | 'mouth' | 'skin';
export type PetItemRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface PetItemCatalogEntry {
    id: number;
    name: string;
    description: string;
    category: PetItemCategory;
    rarity: PetItemRarity;
    price: number;
    effectValue: number;
    isConsumable: boolean;
    isAvailable: boolean;
    icon?: string; // emoji
    iconUrl?: string; // path to icon
}

export const PET_ITEMS_CATALOG: PetItemCatalogEntry[] = [
    // Food items
    {
        id: 1,
        name: 'Manzana',
        description: 'Una manzana fresca y jugosa',
        category: 'food',
        rarity: 'common',
        price: 10,
        effectValue: 15,
        isConsumable: true,
        isAvailable: true,
        icon: '🍎',
    },
    {
        id: 2,
        name: 'Sandwich',
        description: 'Un delicioso sandwich',
        category: 'food',
        rarity: 'common',
        price: 20,
        effectValue: 25,
        isConsumable: true,
        isAvailable: true,
        icon: '🥪',
    },
    {
        id: 3,
        name: 'Pizza',
        description: 'Una pizza con mucho queso',
        category: 'food',
        rarity: 'uncommon',
        price: 50,
        effectValue: 40,
        isConsumable: true,
        isAvailable: true,
        icon: '🍕',
    },
    {
        id: 4,
        name: 'Asado Completo',
        description: 'El mejor asado uruguayo',
        category: 'food',
        rarity: 'rare',
        price: 100,
        effectValue: 60,
        isConsumable: true,
        isAvailable: true,
        icon: '🍖',
    },
    {
        id: 5,
        name: 'Chivito',
        description: 'El chivito más grande que jamás hayas visto',
        category: 'food',
        rarity: 'epic',
        price: 200,
        effectValue: 80,
        isConsumable: true,
        isAvailable: true,
        icon: '🍔',
    },

    // Toy items
    {
        id: 6,
        name: 'Pelota',
        description: 'Una pelota para jugar',
        category: 'toy',
        rarity: 'common',
        price: 30,
        effectValue: 10,
        isConsumable: false,
        isAvailable: true,
        icon: '⚽',
    },
    {
        id: 7,
        name: 'Frisbee',
        description: 'Un frisbee volador',
        category: 'toy',
        rarity: 'uncommon',
        price: 60,
        effectValue: 15,
        isConsumable: false,
        isAvailable: true,
        icon: '🥏',
    },
    {
        id: 8,
        name: 'Consola de Videojuegos',
        description: 'Para jugar a los mejores juegos',
        category: 'toy',
        rarity: 'rare',
        price: 150,
        effectValue: 25,
        isConsumable: false,
        isAvailable: true,
        icon: '🎮',
    },

    // Furniture items
    {
        id: 9,
        name: 'Silla',
        description: 'Una silla cómoda',
        category: 'furniture',
        rarity: 'common',
        price: 40,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '🪑',
    },
    {
        id: 10,
        name: 'Mesa',
        description: 'Una mesa de madera',
        category: 'furniture',
        rarity: 'common',
        price: 60,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: ' टेबल',
    },
    {
        id: 11,
        name: 'Sofá',
        description: 'Un sofá muy cómodo',
        category: 'furniture',
        rarity: 'uncommon',
        price: 120,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '🛋️',
    },
    {
        id: 12,
        name: 'TV Plasma',
        description: 'Una TV de última generación',
        category: 'furniture',
        rarity: 'rare',
        price: 250,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '📺',
    },

    // Clothing items
    {
        id: 13,
        name: 'Camiseta Salto',
        description: 'La camiseta oficial de Salto',
        category: 'clothing',
        rarity: 'uncommon',
        price: 100,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '👕',
    },
    {
        id: 14,
        name: 'Traje de Gala',
        description: 'Para las ocasiones especiales',
        category: 'clothing',
        rarity: 'epic',
        price: 300,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '🤵',
    },

    // Accessory items
    {
        id: 15,
        name: 'Gorra',
        description: 'Una gorra cool',
        category: 'accessory',
        rarity: 'common',
        price: 50,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '🧢',
    },
    {
        id: 16,
        name: 'Lentes de Sol',
        description: 'Para lucir con estilo',
        category: 'accessory',
        rarity: 'uncommon',
        price: 80,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        icon: '🕶️',
    },
    {
        id: 17,
        name: 'Corona Dorada',
        description: 'Solo para los más pudientes',
        category: 'accessory',
        rarity: 'legendary',
        price: 500,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'detail_yellow_antenna_large.png', // Using antenna as placeholder/fallback if specific icon not available
        icon: '👑',
    },

    // Eyes
    {
        id: 18,
        name: 'Ojos Tiernos',
        description: 'Una mirada adorable',
        category: 'eyes',
        rarity: 'common',
        price: 50,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'eye_cute_dark',
    },
    {
        id: 19,
        name: 'Ojos Azules',
        description: 'Profundos como el océano',
        category: 'eyes',
        rarity: 'common',
        price: 50,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'eye_blue',
    },
    {
        id: 20,
        name: 'Ojos Humanos',
        description: 'Un toque de realismo',
        category: 'eyes',
        rarity: 'rare',
        price: 150,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'eye_human',
    },
    {
        id: 21,
        name: 'Ojos Locos',
        description: 'Para mascotas con personalidad',
        category: 'eyes',
        rarity: 'epic',
        price: 300,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'eye_psycho_light',
    },
    {
        id: 22,
        name: 'Ojos Enojados',
        description: '¡Cuidado!',
        category: 'eyes',
        rarity: 'uncommon',
        price: 100,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'eye_angry_red',
    },

    // Mouths
    {
        id: 23,
        name: 'Sonrisa Feliz',
        description: 'La clásica sonrisa',
        category: 'mouth',
        rarity: 'common',
        price: 40,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'mouth_closed_happy',
    },
    {
        id: 24,
        name: 'Boca Abierta',
        description: ':O',
        category: 'mouth',
        rarity: 'common',
        price: 40,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'mouthA',
    },
    {
        id: 25,
        name: 'Colmillos',
        description: 'Para un look vampírico',
        category: 'mouth',
        rarity: 'rare',
        price: 120,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'mouth_closed_fangs',
    },
    {
        id: 26,
        name: 'Dientes',
        description: 'Sonrisa forzada',
        category: 'mouth',
        rarity: 'uncommon',
        price: 80,
        effectValue: 0,
        isConsumable: false,
        isAvailable: true,
        iconUrl: 'mouth_closed_teeth',
    },
];